import { refresh } from './modules/refresh.js';
import { attachRunListeners } from './modules/runs.js';
import { setupNewWorkspaceModal } from './modules/newWorkspaceModal.js';
import { setupImportWorkspaceModal } from './modules/importWorkspaceModal.js';
import { setupManageReposModal } from './modules/manageReposModal.js';
import { setupSettingsModal } from './modules/settingsModal.js';
import { setupWorkspaceToolbar } from './modules/workspaceToolbar.js';
import { setupMetadataModal, openMetadataModal } from './modules/metadataModal.js';
import { setupBulkToast } from './modules/bulkGitToast.js';
import { setupThemeToggle } from './modules/theme.js';
import { setupKeyboardShortcuts } from './modules/keyboardShortcuts.js';
import { setupAutoActions } from './modules/autoActions.js';
import { setupResizer } from './modules/resizer.js';
import { setupDisplayMode } from './modules/displayMode.js';
import { setupKeyboardHelp } from './modules/keyboardHelp.js';
import { setupCommandPalette } from './modules/commandPalette.js';
import { setupDiffModal } from './modules/diffModal.js';
import { setupCommitModal } from './modules/commitModal.js';
import { setupShowArchivedToggle } from './modules/archivedToggle.js';

attachRunListeners();
setupBulkToast();
setupThemeToggle();
setupNewWorkspaceModal();
setupImportWorkspaceModal();
setupManageReposModal();
setupSettingsModal();
setupMetadataModal();
setupWorkspaceToolbar({ openMetadataModal });
setupKeyboardShortcuts();
setupAutoActions();
setupResizer();
setupDisplayMode();
setupKeyboardHelp();
setupCommandPalette();
setupDiffModal();
setupCommitModal();
setupShowArchivedToggle();
refresh();
